server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: qi-api-interface
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
          #添加请求头
          filters:
            - SetRequestHeader=X-ValidGateway-Header,passwsjdegateway
  redis:
    port: 6379
    host: 192.168.50.129
    database: 3
    password: 123456
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    qosEnable: false
    enable-file-cache: false
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://192.168.50.129:8848